import sapi1 from "../public/images/gambar sapi (1).jpg";
import sapi2 from "../public/images/gambar sapi  5.jpg";
import kambing1 from "../public/images/Kambing Alpine.jpg";
import kambing2 from "../public/images/Fakta-Unik-Tentang-Kambing.jpg";
import domba1 from "../public/images/domba.jpg";
import domba2 from "../public/images/730x480-img-71987-domba-merino.jpg";

const menu = [
  {
    id: 1,
    title: "Super Gizi Qurban - 1 Sapi",
    category: "sapi",
    price: 19500000,
    img: sapi1,
    pequrban: 450,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 2,
    title: "Super Gizi Qurban - 1/2 Sapi",
    category: "sapi",
    price: 2750000,
    img: sapi2,
    pequrban: 999,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 3,
    title: "Qurban Domba Large",
    category: "domba",
    price: 2600000,
    img: domba1,
    pequrban: 801,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 4,
    title: "Qurban Domba Palestina",
    category: "domba",
    price: 5200000,
    img: domba2,
    pequrban: 120,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 5,
    title: "Sapi Untuk Negeri",
    category: "sapi",
    price: 19250000,
    img: sapi1,
    pequrban: 100,
    promoPrice: 15000000,
    promo: true,
    sold: true,
  },
  {
    id: 6,
    title: "Super Qurban - 1 Sapi",
    category: "sapi",
    price: 19500000,
    img: sapi2,
    pequrban: 450,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 7,
    title: "Super Gizi Qurban - 1/3 Sapi",
    category: "sapi",
    price: 2750000,
    img: sapi2,
    pequrban: 999,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 8,
    title: "Qurban Kambing Afrika",
    category: "kambing",
    price: 1750000,
    img: kambing1,
    pequrban: 56,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 9,
    title: "Qurban Domba Mesir",
    category: "domba",
    price: 5200000,
    img: domba2,
    pequrban: 120,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 10,
    title: "Qurban Domba Medium",
    category: "domba",
    price: 2600000,
    img: domba2,
    pequrban: 801,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 11,
    title: "Qurban Kambing Afrika",
    category: "kambing",
    price: 1750000,
    img: kambing1,
    pequrban: 56,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 12,
    title: "Sapi ",
    category: "sapi",
    price: 19250000,
    img: sapi1,
    pequrban: 100,
    promoPrice: 15000000,
    promo: true,
    sold: true,
  },
  {
    id: 13,
    title: "Super Gizi Qurban - 1/4 Sapi",
    category: "sapi",
    price: 19500000,
    img: sapi2,
    pequrban: 450,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 14,
    title: "Super Gizi Qurban - 1/5 Sapi",
    category: "sapi",
    price: 2750000,
    img: sapi1,
    pequrban: 999,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 15,
    title: "Qurban Domba Medium",
    category: "domba",
    price: 2600000,
    img: domba2,
    pequrban: 801,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 16,
    title: "Qurban Domba Small",
    category: "domba",
    price: 2600000,
    img: domba2,
    pequrban: 801,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
  {
    id: 17,
    title: "Sapi Untuk Palestina",
    category: "sapi",
    price: 19250000,
    img: sapi2,
    pequrban: 100,
    promoPrice: 15000000,
    promo: true,
    sold: true,
  },
  {
    id: 18,
    title: "Qurban Domba Mesir",
    category: "domba",
    price: 5200000,
    img: domba2,
    pequrban: 120,
    promoPrice: 0,
    promo: false,
    sold: false,
  },
];
export default menu;
